### ISSUE TITLE
Didn't work with my 3 Gb

### ISSUE THREAD

**Issue by lrrr-omicron** [dreemurrs-embedded/Jumpdrive#30]
I just got my convergence edition pinephone.  I mistyped my passphrase when setting it up and when it rebooted my passphrase doesn't work and the filesystem is encrypted with a passphrase unknown to me.

I don't know if I am doing something wrong but I flashed the 0.6 image onto a sd card using
sudo dd bs=4M if=pine64-pinephone.img of=/dev/mmcblk0p1 conv=sync
and then when I put the sd card in and boot it tries to boot off the encrypted memory and asks for password.

I want to erase the pinephone and start over.  Unfortunately I seem to have bricked my new pinephone before getting the chance to try it out.

Is there a button combination to get pinephones to boot off sd instead of internal memory?

**Comment by Danct12** [comment]
Your problem here is that you flashed it to **a partition** (mmcblk0**p1**).

Please flash it to the entire card and try again.
