### ISSUE TITLE
Display support for PineTab Early-Adopter Edition

### ISSUE THREAD

**Issue by jkoan** [dreemurrs-embedded/Jumpdrive#31]
Hi folks,

currently Jumpdrive on the PineTab Early-Adopter Edition has broken Display support.
It only shows up as black. This could probably be due to the [LCD panel driver swap from pine64 ](https://www.pine64.org/2020/07/24/all-about-the-pinetab-update/)
USB-gadget and Telnet are working without any problem.

Tested with Jumpdrive 0.5

**Comment by myxor** [comment]
I can confirm this on my PineTab Early Adopters Edition as well.

**Comment by MartijnBraam** [comment]
Pushed a new alpha build that might solve this (I don't have that model pinetab to verify it)

**Comment by jkoan** [comment]
Its Working, thx

**Comment by Danct12** [comment]
Now a part of [Jumpdrive 0.6](https://github.com/dreemurrs-embedded/Jumpdrive/releases/tag/0.6)
