### ISSUE TITLE
Good first impression README?

### ISSUE THREAD

**Issue by Danct12** [dreemurrs-embedded/Jumpdrive#6]
We probably should make one, so that they can get the first impression by reading the README.

Things we need:
- A banner: We can take the xcf from the splash screen, then add the word "Jumpdrive" next to it, something like what postmarketOS have done before:
![image](https://user-images.githubusercontent.com/19162768/76814373-33cb4d00-682d-11ea-96a1-3f26046bbd0d.png)

- Better instructions on how to use it: So that they can find the utility easy to use.

**Comment by Danct12** [comment]
Made a banner for Jumpdrive, feedback?

![jumpdrive_logo](https://user-images.githubusercontent.com/19162768/77336635-6360e480-6d5a-11ea-9861-62256a0525ba.png)

**Comment by MartijnBraam** [comment]
white background with black text probably fits better in a readme

**Comment by Danct12** [comment]
How about this then?

![jumpdrive png_logo](https://user-images.githubusercontent.com/19162768/80208686-f1cacd80-865a-11ea-87cf-dac7f45b2fa6.png)
