### ISSUE TITLE
Jumpdrive is not compatible with SailfishOS

### ISSUE THREAD

**Issue by GNUuser** [dreemurrs-embedded/Jumpdrive#8]
I flashed SailfishSO to eMMC-Pinephone using Jumpdrive, but Sailfish no boot. :  ( 
Just reporting ---

**Comment by Danct12** [comment]
Looks like SailfishOS needs to be supported to boot from eMMC.

As right now, it looks for root in mmcblk0, which is the SD card: https://github.com/sailfish-on-dontbeevil/u-boot-bootloader/blob/master/pinephone/boot.cmd#L2

@DylanVanAssche, please check this out.

**Comment by DylanVanAssche** [comment]
We do not support eMMC yet, isn't a priority at the moment.
Will have to check how others are handling this.

**Comment by DylanVanAssche** [comment]
Should be fixed with this PR: https://github.com/sailfish-on-dontbeevil/u-boot-bootloader/pull/1

**Comment by GNUuser** [comment]
Yes, is working Sailfish with eMMC. Big thanks to @DylanVanAssche
